version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 0 # allow only security updates
    groups:
      fsspec-stack:
        patterns:
          - "fsspec"
          - "gcsfs"
          - "s3fs"
