version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 0
