name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v10.3.1
        with:
          github_token: ${{ secrets.GH_PAT }}

      - name: Rename GitHub Release
        if: steps.release.outputs.released == 'true'
        run: gh release edit ${{ steps.release.outputs.tag }} --title "${{ steps.release.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
